LeaveManagement.Web/Controllers/LeaveRequestsController.cs
using LeaveManagement.Common.Constants;
using LeaveManagement.Application.Contracts;
using LeaveManagement.Data;
using LeaveManagement.Common.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Serilog;

namespace LeaveManagement.Web.Controllers
{
    [Authorize]
    public class LeaveRequestsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILeaveRequestRepository leaveRequestRepository;
        private readonly ILogger<LeaveRequestsController> logger;

        public LeaveRequestsController(ApplicationDbContext context,
            ILeaveRequestRepository leaveRequestRepository,
            ILogger<LeaveRequestsController> logger
            )
        {
            _context = context;
            this.leaveRequestRepository = leaveRequestRepository;
            this.logger = logger;
        }
        // GET: LeaveRequests
        [Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Index()
        {
            var model = await leaveRequestRepository.GetAdminLeaveRequestList();
            return View(model);
            //var applicationDbContext = _context.LeaveRequests.Include(l => l.LeaveType).Include(l => l.RequestingEmployee);
            //return View(await applicationDbContext.ToListAsync());

        }
        public async Task<ActionResult> MyLeaves()
        {
            var model = await leaveRequestRepository.GetMyLeaveRequestDetails();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cancel(int id)
        {
            //We don't delete the request, just add cancelled flag
            try
            {
                await leaveRequestRepository.CancelRequest(id);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Error canceling request");
                throw;
            }
            return RedirectToAction(nameof(MyLeaves));

        }

        // GET: LeaveRequests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var model = await leaveRequestRepository.GetLeaveRequestAsync(id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeRequestApproval(int id, bool approved)
        {
            try
            {
                await leaveRequestRepository.ChangeRequestApproval(id, approved);

            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Error approving request");
                throw;
            }
            return RedirectToAction("Index");
        }

        // GET: LeaveRequests/Create
        public IActionResult Create()
        {
            var model = new LeaveRequestCreateVM
            {
                LeaveTypes = new SelectList(_context.LeaveTypes, "Id", "Name"),
            };
            //ViewData["LeaveTypeId"] = new SelectList(_context.LeaveTypes, "Id", "Name");
            //ViewData["RequestingEmployeeId"] = new SelectList(_context.Users, "Id", "Id");
            return View(model);
        }

        // POST: LeaveRequests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LeaveRequestCreateVM leaveRequestVM)
        {
            logger.LogInformation("Entering the controller");
            try
            {
                if (ModelState.IsValid)
                {
                    logger.LogInformation("Model is Valid");

                    var isReqValid = await leaveRequestRepository.CreateLeaveRequest(leaveRequestVM);
                    if (isReqValid)
                    {
                    logger.LogInformation("Request is Valid, should redirect to MyLeaves");

                        return RedirectToAction(nameof(MyLeaves));
                    }
                    ModelState.AddModelError(string.Empty, "Allocation limit is exceeded with this request");
                }
            }
            catch (Exception ex)
            {

                logger.LogError(ex, "Error creating leave request");
                ModelState.AddModelError(string.Empty, "An error has occured. Please try again later");
            }
            leaveRequestVM.LeaveTypes = new SelectList(_context.LeaveTypes, "Id", "Name", leaveRequestVM.LeaveTypeId);
            //ViewData["RequestingEmployeeId"] = new SelectList(_context.Users, "Id", "Id", leaveRequestVM.RequestingEmployeeId);
            return View(leaveRequestVM);
        }

        // GET: LeaveRequests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.LeaveRequests == null)
            {
                return NotFound();
            }

            var leaveRequest = await _context.LeaveRequests.FindAsync(id);
            if (leaveRequest == null)
            {
                return NotFound();
            }
            ViewData["LeaveTypeId"] = new SelectList(_context.LeaveTypes, "Id", "Id", leaveRequest.LeaveTypeId);
            ViewData["RequestingEmployeeId"] = new SelectList(_context.Users, "Id", "Id", leaveRequest.RequestingEmployeeId);
            return View(leaveRequest);
        }

        // POST: LeaveRequests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StartDate,EndDate,LeaveTypeId,RequestComments,Approved,Cancelled,RequestingEmployeeId,Id,DateCreated,DateUpdated")] LeaveRequest leaveRequest)
        {
            if (id != leaveRequest.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(leaveRequest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeaveRequestExists(leaveRequest.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LeaveTypeId"] = new SelectList(_context.LeaveTypes, "Id", "Id", leaveRequest.LeaveTypeId);
            ViewData["RequestingEmployeeId"] = new SelectList(_context.Users, "Id", "Id", leaveRequest.RequestingEmployeeId);
            return View(leaveRequest);
        }

        // GET: LeaveRequests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.LeaveRequests == null)
            {
                return NotFound();
            }

            var leaveRequest = await _context.LeaveRequests
                .Include(l => l.LeaveType)
                .Include(l => l.RequestingEmployee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leaveRequest == null)
            {
                return NotFound();
            }

            return View(leaveRequest);
        }

        // POST: LeaveRequests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //if (_context.LeaveRequests == null)
            //{
            //    return Problem("Entity set 'ApplicationDbContext.LeaveRequests'  is null.");
            //}
            //var leaveRequest = await _context.LeaveRequests.FindAsync(id);
            //if (leaveRequest != null)
            //{
            //    _context.LeaveRequests.Remove(leaveRequest);
            //}

            //await _context.SaveChangesAsync();
            await leaveRequestRepository.DeleteAsync(id);

            return RedirectToAction(nameof(MyLeaves));
        }

        private bool LeaveRequestExists(int id)
        {
            return (_context.LeaveRequests?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

LeaveManagement.Web/Views/LeaveRequests/Create.cshtml
@model LeaveRequestCreateVM

@{
    ViewData["Title"] = "Create";
}

<h1>Apply for a Leave</h1>

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LeaveTypeId" class="control-label"></label>
                <select asp-for="LeaveTypeId" class="form-select" asp-items="Model.LeaveTypes">
                    <option>Select Leave Type</option>
                </select>
                <span asp-validation-for="LeaveTypeId" class="text-danger"></span>
            </div>
            <br />
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="StartDate" class="control-label"></label>
                        <input asp-for="StartDate" class="form-control datepicker" type="text" />
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>
                </div>
                <br />
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="EndDate" class="control-label"></label>
                        <input asp-for="EndDate" class="form-control datepicker" type="text" />
                        <span asp-validation-for="EndDate" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="RequestComments" class="control-label"></label>
                <textarea asp-for="RequestComments" class="form-control"></textarea>
                <span asp-validation-for="RequestComments" class="text-danger"></span>
            </div>
            <br />

            <div class="form-group">
                <a asp-action="MyLeaves" class="btn btn-dark">Back to List</a> &nbsp;
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

LeaveManagement.Web/Views/LeaveRequests/Details.cshtml
@model LeaveRequestVM

@{
    ViewData["Title"] = "Leave Request Details";
    string className, headingText;
    if (Model.Approved == null)
    {
        headingText = "Pending Approval";
        className = "warning";
    }
    else if (Model.Approved == true)
    {
        headingText = "Approved";
        className = "success";
    }
    else
    {
        headingText = "Declined";
        className = "danger";
    }
}

<h1>Leave Request Details</h1>

@*show employee info*@
<div class="alert alert-@className" role="alert">
    <h4 class="alert-heading">Approval Status: @headingText</h4>
    <p><strong>Employee name: </strong>@Model.Employee.FirstName @Model.Employee.LastName</p>
    <hr>
    <p class="mb-0"><strong>Date requested:</strong> @Model.DateCreated</p>
</div>

<div>
    <h4>Leave Request</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveType.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestComments)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestComments)
        </dd>
    </dl>
</div>
<div style="display: inherit">
        @if (Model.Approved == null)
        {
            <div>
                <form asp-action="ChangeRequestApproval">
                    <input asp-for="Id" type="hidden" />
                    @*<input name="Id" type="hidden" value="@Model.Id" />*@
                    <input name="approved" type="hidden" value="true" />
                <button @*asp-route-approved="true"*@ type="submit" class="btn btn-success">Approve</button>&nbsp;
                </form>
            </div>
        <div class="mx-2">
                <form asp-action="ChangeRequestApproval">
                    <input asp-for="Id" type="hidden" />
                    @*<input name="Id" type="hidden" value="@Model.Id" />*@
                    <input name="approved" type="hidden" value="false" />
                <button @*asp-route-approved ="false"*@ type="submit" class="btn btn-danger">Reject</button>&nbsp;
                </form>
            </div>
        }
    <div> <a asp-action="Index" class="btn btn-dark">Back to List</a> &nbsp;</div>
</div>

LeaveManagement.Web/Views/LeaveRequests/Edit.cshtml
@model LeaveManagement.Data.LeaveRequest

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>LeaveRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeaveTypeId" class="control-label"></label>
                <select asp-for="LeaveTypeId" class="form-control" asp-items="ViewBag.LeaveTypeId"></select>
                <span asp-validation-for="LeaveTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestComments" class="control-label"></label>
                <input asp-for="RequestComments" class="form-control" />
                <span asp-validation-for="RequestComments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Approved" class="control-label"></label>
                <input asp-for="Approved" class="form-control" />
                <span asp-validation-for="Approved" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cancelled" class="control-label"></label>
                <input asp-for="Cancelled" class="form-control" />
                <span asp-validation-for="Cancelled" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestingEmployeeId" class="control-label"></label>
                <select asp-for="RequestingEmployeeId" class="form-control" asp-items="ViewBag.RequestingEmployeeId"></select>
                <span asp-validation-for="RequestingEmployeeId" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateUpdated" class="control-label"></label>
                <input asp-for="DateUpdated" class="form-control" />
                <span asp-validation-for="DateUpdated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

LeaveManagement.Web/Views/LeaveRequests/Index.cshtml
@model AdminLeaveRequestViewVM

@{
    ViewData["Title"] = "Index";
}

<h1>Admin Leave Requests View</h1>

@*Statistics*@
<div class="row">
    <div class="col-sm-3">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">@Model.TotalRequests</h2>
                <p class="card-text">@Html.DisplayNameFor(m => m.TotalRequests)</p>
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title text-success">@Model.ApprovedRequests</h2>
                <p class="card-text">@Html.DisplayNameFor(m => m.ApprovedRequests)</p>
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title text-warning">@Model.PendingRequests</h2>
                <p class="card-text">@Html.DisplayNameFor(m => m.PendingRequests)</p>
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title text-danger">@Model.RejectedRequests</h2>
                <p class="card-text">@Html.DisplayNameFor(m => m.RejectedRequests)</p>
                @*<a href="#" class="btn btn-primary">Go somewhere</a>*@
            </div>
        </div>
    </div>
</div>

<hr />
<h2>Leave Requests Log</h2>
<hr />

<table class="table">
    <h3>Pending Requests</h3>
    <thead>
        <tr>
            <th>
                Employee Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveRequests[0].StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveRequests[0].EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveRequests[0].LeaveType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveRequests[0].Approved)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveRequests[0].DateCreated)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.LeaveRequests.Where(item => item.Approved == null && !item.Cancelled))
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.FirstName) @Html.DisplayFor(modelItem => item.Employee.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LeaveType.Name)
            </td>
            <td>
                @if (item.Approved == null)
                {
                    <span class="badge text-bg-warning">Pending</span>
                }
                else if (item.Approved.Value)
                {
                    <span class="badge text-bg-success">Approved</span>
                }
                else if (!item.Approved.Value)
                {
                    <span class="badge text-bg-danger">Rejected</span>
                }
                else if (item.Cancelled)
                {
                    <span class="badge text-bg-secondary">Cancelled</span>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                <a asp-action="Details" class="btn btn-info btn-sm" asp-route-id="@item.Id">Review</a>
            </td>
        </tr>
        }
    </tbody>
</table>
<br />
<br />
<hr />
<br />
<table class="table">
    <h3>Requests Reviewed</h3>
    <thead>
        <tr>
            <th>
                Employee Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveRequests[0].StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveRequests[0].EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveRequests[0].LeaveType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveRequests[0].Approved)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveRequests[0].DateCreated)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        
        @foreach (var item in Model.LeaveRequests.Where(item => item.Approved != null || item.Cancelled != null))
        {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Employee.FirstName) @Html.DisplayFor(modelItem => item.Employee.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LeaveType.Name)
                    </td>
                    <td>
                    @if (item.Cancelled)
                    {
                        <span class="badge text-bg-secondary">Cancelled</span>
                    }
                    else if (item.Approved == null)
                    {
                        <span class="badge text-bg-warning">Pending</span>
                    }
                    else if (item.Approved.Value)
                    {
                        <span class="badge text-bg-success">Approved</span>
                    }
                    else if (!item.Approved.Value)
                    {
                        <span class="badge text-bg-danger">Rejected</span>
                    }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateCreated)
                    </td>
                    <td>
                        <a asp-action="Details" class="btn btn-warning btn-sm" asp-route-id="@item.Id">Details</a>
                    </td>
                </tr>
            }
    </tbody>
</table>

LeaveManagement.Web/Views/LeaveRequests/MyLeaves.cshtml
@model EmployeeLeaveRequestViewVM

@{
    ViewData["Title"] = "My Leaves";
}

<div class="card" style="width: 100%;">
        <h2 style="padding: .75rem">Leave Allocations</h2>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="row">
                <div class="col">Leave Name</div>
                <div class="col">Original Allocation</div>
                <div class="col">Current Allocation</div>
                @*<div class="col">Action</div>*@
            </div>
        </li>
        @foreach (var allocation in Model.LeaveAllocations)
        {
            <li class="list-group-item">
                <div class="row">
                    <div class="col">
                        <span class="" style="display: inline-block; min-width: 100px;">
                            <strong>@allocation.LeaveType.Name</strong>
                        </span>
                    </div>
                    <div class="col">
                        <button type="button" class="btn btn-primary">
                            Allocated Days<span class="badge bg-secondary">@allocation.LeaveType.DefaultDays</span>
                        </button>
                    </div>
                    <div class="col">
                        <button type="button" class="btn btn-primary">
                            Remaining Days <span class="badge text-bg-light">@allocation.NumberOfDays</span>
                        </button>
                    </div>
@*                    <div class="col">
                        <a class="btn btn-warning" asp-action="EditAllocation" asp-route-id="@allocation.Id"><i class="fa-regular fa-pen-to-square"></i>Edit Allocation</a> &nbsp;
                    </div>
*@                </div>




            </li>

        }
    </ul>
</div>

<hr />

<h2 style="padding: .6rem; padding-left: 1rem">Current Requests</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LeaveRequests[0].StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveRequests[0].EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveRequests[0].LeaveType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveRequests[0].DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveRequests[0].Approved)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.LeaveRequests)
        {
            <tr>
                <td>
                    @(item.StartDate.HasValue ? @item.StartDate.Value.ToString("MM/dd/yyyy") : "")
                </td>
                <td>
                    @(item.EndDate.HasValue ? @item.EndDate.Value.ToString("MM/dd/yyyy") : "")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveType.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </td>
                <td>
                    @if (item.Cancelled)
                    {
                        <span class="badge text-bg-secondary">Cancelled</span>
                    }
                    else if (item.Approved == null)
                    {
                        <span class="badge text-bg-warning">Pending</span>
                    }
                    else if (item.Approved.Value)
                    {
                        <span class="badge text-bg-success">Approved</span>
                    }
                    else if (!item.Approved.Value)
                    {
                        <span class="badge text-bg-danger">Rejected</span>
                    }
                </td>
                <td>
                    @*<a asp-action="Cancel" class="btn btn-danger btn-sm" asp-route-id="@item.Id">Cancel Request</a>*@
                    @if (item.Approved == null && item.Cancelled == false)
                    {
                        <form id="deleteForm" asp-action="Cancel" asp-controller="LeaveRequests">
                            <input type="hidden" id="leaveRequestId" name="Id" @*asp-form="@item.Id"*@ />
                            <button data-id="@item.Id" class="btn btn-danger btn-sm deleteBtn" type="button">Cancel Request</button>
                        </form>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>



@section Scripts {
    <script>
        $(function () {
            $(".deleteBtn").click(function (e) {
                swal({
                    title: 'Canceling Request',
                    text: "Are you sure you want to cancel this request?",
                    icon: 'warning',
                    buttons: true,
                    dangerMode: true
                }).then((confirm) => {
                    if (confirm) {
                        //alert("You said yes")
                        var btn = $(this);
                        var id = btn.data("id")
                        $("#leaveRequestId").val(id);
                        $("#deleteForm").submit();

                    }
                })
            })
        })
    </script>
}